#cloud-config

coreos:
  etcd2:
    # Definition of the initial cluster (the etcd machines running the show... data pulled from https://discovery.etcd.io/c51e848f38dadf9b55112cff844c3ae6)
    initial-cluster: 35514dc17f3948a89713d8748eecdb76=http://10.131.3.114:2380, 0429f042ac4c4d4db072a4dc00813631=http://10.131.1.161:2380, 54298ae95292415c83e3372be4ed0cd9=http://10.131.4.22:2380
    # Set up proxy behaviour
    advertise-client-urls: http://0.0.0.0:2379
    listen-client-urls: http://0.0.0.0:2379
    proxy: on

  fleet:
    public-ip: $private_ipv4   # Needed for fleetctl ssh command
    metadata: role=node_grp_a

  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: sshd.socket
      command: restart
      runtime: true
      content: |
        [Socket]
        ListenStream=2222
        FreeBind=true
        Accept=yes

  locksmith:
    group: nodes

  update:
    reboot-strategy: reboot
